version: '3.9'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db/pdf_db
  db:
      image: postgres:15
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: pdf_db
        TZ: Asia/Tokyo
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
