# Docker Composeのバージョンを指定
version: '3.9'

services:
  # Webサービスの設定
  web:
    build: .  # 現在のディレクトリからビルド
    ports:
      - "5001:5000"  # ホストの5001ポートをコンテナの5000ポートにマッピング
    environment:
      - FLASK_APP=app  # Flaskアプリケーションのエントリポイント
      - FLASK_ENV=development  # 開発環境を指定
      - DATABASE_URL=postgresql://user:GDOUzrnVRdL4jivgQrLy7chD9t9AfVmW@dpg-cumug7aj1k6c73b442gg-a.singapore-postgres.render.com/pdf_db_957f  # データベース接続URL
